# Build for markturn
version: 2.1

jobs:
  build:
      docker:
        - image: markturn
      steps:
        - checkout
        - run: apt update
        - run: mkdir build
        - run: cd build && cmake -DCMAKE_BUILD_TYPE=Release .. -G Ninja
        - run: cd build && ninja && ninja install && ldconfig
        - run: cd build && ninja run
        - run: cd build && cpack -G DEB
        - store_artifacts:
            path: build/markturn-1.0.0-Linux.deb
